import React from 'react'
import "./MainAbout.css"
import manImg from "./images/man.png"
import { MdClear } from "react-icons/md"
import { Link } from 'react-router-dom'
export default function MainAbout() {
    
    return (
        <div className="main-about">
            <div className="bg-star"></div>
            <div className="main-content">
             <div className="main-text">
                <Link to='/main' className="cancel-btn">
                    <MdClear size={30} color="#ccc" />
                </Link>
                 <h2 className="about-text-title">Biz Haqimizda</h2>
                 <div className="about-body">
                 Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem laudantium, nesciunt nam consequuntur eligendi culpa sequi quam doloribus molestiae tenetur corporis deserunt dolorum optio veniam porro vitae omnis iure laborum?
                 Fugiat aliquid sit nemo blanditiis tempora tenetur, eum eveniet, temporibus voluptates quaerat harum officia quae natus nobis odio. Facere dolorem quo ut possimus ipsum inventore deleniti quisquam ab rem reprehenderit!
                 Iure numquam officiis enim neque quaerat ab quis dolorem, excepturi dolor placeat voluptatibus ut debitis incidunt dignissimos? Reprehenderit voluptatum ducimus facere quo dolor aperiam, quasi architecto fugiat, adipisci iure debitis.
                 Deserunt mollitia harum recusandae saepe consectetur culpa quaerat dolor possimus quasi blanditiis. Exercitationem minima minus quaerat, magni facilis, aut iure consequatur unde dolores odio amet, quo quae ipsum quam doloremque.
                 Error consectetur quaerat alias iusto voluptatibus optio nemo provident nesciunt atque, eligendi vel culpa distinctio sed voluptas blanditiis vitae quam excepturi natus explicabo. Suscipit doloribus ut nesciunt minus fuga labore!
                 Dolorum architecto quo magnam? Reiciendis eaque minus, aut quo aperiam accusantium architecto vel labore nam, quisquam earum quidem natus, neque cupiditate dolor voluptate necessitatibus quod non repellat voluptatibus molestias? Delectus.
                 Enim, deleniti nostrum ratione voluptatibus illum libero ipsa magni optio incidunt impedit laboriosam commodi harum corporis omnis iste consectetur facere distinctio nulla nisi! Cum excepturi aliquid cumque provident recusandae ut.
                 Voluptas fugiat animi nisi ex, id optio esse architecto ut mollitia, sapiente omnis iure error maiores, inventore obcaecati! Eveniet laboriosam atque sed pariatur illo ullam deleniti? Repudiandae eaque sunt praesentium.
                 Et aspernatur necessitatibus fugit accusamus nisi pariatur dolorum at tempore eveniet consectetur saepe incidunt exercitationem commodi, natus debitis? Soluta, consequuntur error ab harum ut voluptas similique recusandae voluptates sint incidunt?
                 Repudiandae odit, pariatur esse illo exercitationem nobis quaerat, officiis laudantium at delectus velit dolore totam quibusdam saepe maiores. Ratione laborum quos nisi officia quisquam maiores sunt molestias ad ipsa iusto?
                 Fugiat voluptates, modi mollitia, doloremque quas aut itaque quod odit quae sunt quo labore culpa recusandae nemo illum veniam, perferendis repellendus ad suscipit consequatur excepturi! Laboriosam non eveniet nesciunt necessitatibus.
                 Quibusdam rerum maiores veniam unde repellendus magnam quam corrupti doloribus quidem sequi veritatis a, odio ullam alias nostrum quis consectetur porro ratione blanditiis rem sed hic ea! Porro, ipsum reiciendis?
                 Recusandae non, tempora magnam corporis officiis earum laboriosam nulla vel asperiores velit. Ut, laboriosam neque tempore, sequi dolor vero provident veritatis blanditiis suscipit quaerat eos quia enim maiores iste fuga.
                 Veritatis dolores, adipisci aut ipsum optio recusandae vitae culpa pariatur repudiandae minus deserunt expedita vero illo impedit quis, omnis quia, autem repellendus sunt ipsam maiores numquam? Cum blanditiis similique nulla!
                 Veritatis voluptates nemo mollitia quidem sapiente, officia quos, earum nisi necessitatibus impedit fugiat cumque culpa ipsa! Quis consequatur earum doloremque deleniti cum vitae dicta enim quod reprehenderit. Unde, dolorem doloremque.
                 Vitae, ad quis eum, ullam est eius cum earum sit, praesentium minus harum commodi fuga veniam expedita incidunt consequuntur cumque officiis nisi quia quos. Error quas vitae adipisci voluptatibus provident?
                 Maxime nihil voluptate quas, ut officia ratione, voluptas, pariatur atque facilis eaque iure cum? Harum consectetur ad iste, cum magni voluptates esse natus enim eum deserunt, doloribus dicta consequatur soluta.
                 Vel iste nobis quia unde fugit consequatur. Quisquam commodi quasi vitae tempora sit, doloremque reiciendis quod unde optio facilis, minima earum velit consequuntur recusandae quam ut. Odio fuga cum voluptas!
                 Expedita earum culpa quo unde. Sunt quis adipisci, nemo dolores dolorum iste voluptas! Rerum minima commodi, eaque porro aut omnis, nulla, libero sed doloribus accusantium aliquam et explicabo obcaecati minus?
                 Dolores quis aliquid ducimus modi nam excepturi necessitatibus recusandae impedit fuga laudantium rem veniam, deserunt omnis quidem quisquam aspernatur quia fugit tempore cupiditate exercitationem dicta. Eius harum sed ex dicta?
                 Id necessitatibus incidunt illo quis illum earum tempore. Ad voluptate voluptatem suscipit, rerum at dolorem veniam qui quis quia iste, earum ratione aspernatur magni ab, laudantium saepe vero sequi temporibus!
                 Consequuntur expedita ratione quidem earum obcaecati ullam cupiditate? Tenetur rerum quaerat earum eveniet iure perspiciatis minima ad corporis doloribus enim ratione unde at veniam temporibus aspernatur, facere maiores quo molestiae.
                 Eligendi tempore quae praesentium doloremque eum adipisci natus accusamus ipsa voluptatem facilis blanditiis vero corporis pariatur sint similique cupiditate a magni quam, harum error ex! Deserunt nulla ut itaque velit?
                 Quidem cupiditate non velit numquam provident aliquid? Perferendis maxime quod, nihil exercitationem at voluptatibus libero fuga rerum delectus! Temporibus quam corrupti reiciendis beatae consectetur magni eligendi tempore ullam voluptatum minus.
                 Iusto veritatis laboriosam ut maiores sed ullam aliquam atque quasi! Deserunt molestias ratione eaque nostrum mollitia quasi eligendi dolorem sequi, praesentium minus dignissimos odio officiis expedita tempore odit fugit laudantium.
                 Eius quidem itaque sit et laudantium repellendus, quam nesciunt quis impedit distinctio molestias voluptates, blanditiis veritatis maxime iure placeat. Voluptate, iusto a? In architecto dolorem animi molestias vitae qui illum?
                 Veniam ducimus labore repellendus quia. Fuga, perspiciatis maxime! Asperiores alias distinctio soluta expedita doloremque optio maiores impedit, repellat quod velit provident reiciendis neque numquam quisquam quo! Expedita aspernatur harum itaque!
                 Quibusdam repellat doloremque pariatur omnis error mollitia magni facilis ullam fuga nemo ut corrupti officiis distinctio, laborum maxime perferendis ducimus fugiat, debitis non reiciendis nam, ab et recusandae. Quidem, quo.
                 Blanditiis quo quia error non obcaecati assumenda ab soluta dicta doloribus cupiditate vel, aspernatur saepe, fugit animi ut beatae harum est adipisci necessitatibus amet, laboriosam officia. Nemo deleniti aperiam quis.
                 Alias, earum sunt quo aliquam reprehenderit animi. Quaerat obcaecati eius sed perspiciatis voluptas asperiores suscipit deserunt non in reprehenderit nihil velit, vel provident nulla minima nobis necessitatibus sapiente a error!
                 Laborum deserunt maxime est doloribus sequi corporis cum tempora eligendi, voluptatem rerum eveniet in vero veritatis corrupti obcaecati. Assumenda laudantium in amet blanditiis quam sunt consectetur adipisci. Iste, corporis voluptatum!
                 Quidem repellendus molestiae magni dicta hic eos, ducimus aspernatur fugiat deserunt perspiciatis nemo consequatur incidunt magnam saepe iste similique itaque voluptatibus doloribus voluptatem? Veniam error nam at cupiditate natus dignissimos?
                 Iure voluptates dignissimos tempora voluptatum mollitia quia, dolor molestias earum maiores quod maxime nostrum natus exercitationem! Nemo doloribus inventore explicabo sed eligendi nam impedit vitae possimus! Ad eum sed amet!
                 Possimus a molestiae sapiente quo quia officiis exercitationem praesentium aperiam quibusdam eos velit mollitia fugit at maiores ipsam iusto nihil minus, qui sunt quisquam. Quas assumenda animi mollitia ipsam sit.
                 Adipisci voluptas rem recusandae, suscipit voluptate ut optio amet eum deleniti accusamus ducimus iure deserunt, voluptatum quam! Beatae error dolorem obcaecati officiis delectus odit repudiandae, fugit repellendus necessitatibus corrupti natus.
                 Pariatur molestiae similique itaque, quos voluptatem ratione incidunt consequatur sit velit unde assumenda accusantium, dicta labore ipsum corrupti modi odio hic! Consectetur hic, ullam quis et quos quaerat dolorem at.
                 Cumque sunt accusantium laborum magnam ab dolorem nostrum commodi amet eaque corporis. Id in rerum harum sunt illo. Iste reprehenderit modi debitis eos id libero totam quod veniam assumenda. Minus?
                 Possimus libero et quo odio sunt inventore cum similique nisi expedita laborum culpa qui quibusdam asperiores aperiam, blanditiis voluptatum voluptas eveniet, nihil corrupti magni illo ab. Enim molestiae sapiente reprehenderit.
                 Voluptas veniam quo doloremque. Sunt harum dicta dignissimos eum suscipit distinctio illo sint, animi sequi non esse totam consequuntur voluptate hic nulla quaerat in eligendi magnam, modi velit deleniti qui.
                 Voluptate odit fuga quae possimus eos, debitis culpa ad nihil natus, hic expedita, magnam quisquam rem ducimus impedit aut. Ab numquam voluptates quam exercitationem rem magni quasi cumque odit iusto!
                 Nostrum doloribus unde perspiciatis voluptatibus ex ipsa nihil aperiam! Illo veniam dolorem beatae, non sapiente odio nam quibusdam sequi numquam quia excepturi culpa harum et quis nostrum quo dolorum quas.
                 Minima id veniam recusandae. Fugiat tempora repudiandae deleniti commodi reiciendis blanditiis autem quaerat ipsam quis quae, voluptate nisi distinctio, sapiente in illo culpa, vitae illum totam. Nisi vero cupiditate deserunt!
                 Ad temporibus unde autem quis odio quaerat atque saepe repellat animi labore, molestiae iusto, quod fugiat vel repudiandae? Esse totam eligendi dolores iste explicabo laudantium nisi repellendus qui? Debitis, animi.
                 Commodi maiores numquam laborum! Deleniti perferendis, possimus rem accusantium vitae libero ab quae veritatis ducimus aliquam qui totam iure, culpa voluptates, id tenetur sunt facilis. Vero repudiandae error libero nihil.
                 Ratione repudiandae modi quaerat neque ipsam iste possimus iure assumenda pariatur suscipit labore necessitatibus voluptates, laborum architecto dolorem, nam qui, perferendis rerum dicta velit quisquam! Esse pariatur porro ea eligendi.
                 Cupiditate consectetur delectus magnam aspernatur nemo iusto necessitatibus omnis mollitia dicta sint eligendi voluptatum, enim facilis laboriosam dignissimos repellendus, cumque expedita. Sed, eaque pariatur porro at libero impedit amet ipsum!
                 Ducimus ut explicabo minus dolor quae molestias cum. Tempore aut blanditiis incidunt, necessitatibus cumque error, similique possimus delectus nobis, sequi facilis nulla quod dolorem optio totam impedit? Sint, dolor architecto.
                 Doloribus debitis quaerat eum velit, nisi eveniet. Earum unde minima voluptatem. Cupiditate explicabo tempore repudiandae distinctio aspernatur labore dicta quas quasi quia consequatur voluptatibus, voluptates qui asperiores minima delectus nisi.
                 Nesciunt inventore est voluptatibus nihil veniam cumque omnis esse corporis perspiciatis, consequatur, nam architecto! Dolores cupiditate perferendis excepturi debitis? Neque dignissimos amet quidem sed quo aspernatur. Sit perspiciatis quaerat exercitationem?
                 Aliquam natus ea nulla, repellat assumenda doloremque eius cupiditate facere harum quam minima quaerat corrupti! Autem velit blanditiis distinctio reprehenderit vel quo! Accusantium, unde corrupti molestias saepe aut nulla esse.
                 Animi aut, optio et ratione officiis veniam! Fuga cupiditate vero esse odio corrupti in tempora. Optio soluta possimus aperiam modi veritatis iste, reprehenderit cumque, quis unde officia quas odit deleniti!
                 Saepe officia, neque nihil atque sint labore dolore non omnis! Incidunt, nesciunt velit possimus numquam natus quos eum necessitatibus debitis voluptates optio, nobis officia? Nam sapiente nostrum minima vel magnam.
                 Velit atque saepe repudiandae totam dolores error id, repellat ipsa quidem! Aliquam totam vel ratione ullam. Adipisci consectetur tenetur illum ipsam aut error qui! In modi odit illum incidunt animi!
                 Soluta laudantium placeat delectus commodi modi non voluptatem fugiat labore dolore? Eveniet minus, dolorum nostrum atque ipsa consectetur earum eius incidunt voluptates natus, beatae cum velit. Et a accusantium exercitationem?
                 Eligendi quia labore dolores culpa eius distinctio molestias aut odio itaque et facilis temporibus harum nesciunt, exercitationem, dignissimos incidunt! Temporibus aliquid maxime voluptatum facilis, id ut? Minima voluptatum dolorem tempora.
                 Nisi consequuntur architecto qui possimus ut tenetur fuga ab, molestiae eligendi asperiores tempore eveniet at corporis mollitia voluptatum quas nam odit impedit maiores praesentium? Quam, eos rerum? Veniam, mollitia sequi!
                 Ex quia aperiam ullam eaque odit fuga nostrum possimus. Placeat molestias labore quidem officiis quae quod optio nam repellendus earum praesentium, a tempore assumenda nobis deleniti accusantium cupiditate asperiores eum.
                 Aut porro consequuntur veritatis maxime, pariatur animi debitis totam harum ipsa, numquam aliquam. Aliquam, doloremque! Quod vero ipsum eaque explicabo aperiam reprehenderit ea. Dolore, corrupti ullam quidem eaque perspiciatis recusandae.
                 Harum dolorem earum obcaecati magnam laboriosam reiciendis nobis porro placeat! Fugit, quibusdam nulla, soluta quas modi consequuntur laborum totam atque vero et natus doloribus temporibus? Incidunt maxime neque animi officiis.
                 Explicabo aperiam inventore officiis perspiciatis odio. Excepturi, quaerat odio nam consectetur nostrum asperiores possimus molestiae cumque dicta! Sequi laudantium ut, provident veritatis porro libero expedita ad consectetur vitae at mollitia!
                 Iure expedita, doloribus quos ipsam error adipisci beatae natus distinctio perferendis odit, magni unde porro debitis tempora. Aperiam est blanditiis quasi non molestias, sequi, dolorum sed quae exercitationem omnis accusantium!
                 Laborum aperiam, delectus facere quia maxime porro cum ab explicabo quos ipsum ex soluta sint a maiores mollitia iure officia molestiae, autem corrupti consequuntur animi cumque, provident suscipit. Magni, optio?
                 Ut ex quisquam voluptatum vero enim sint delectus sapiente reiciendis repellat! Quas, itaque! Tenetur harum ad molestias illo delectus? Quos velit praesentium a laudantium culpa iusto temporibus, non quibusdam adipisci.
                 Autem architecto placeat error exercitationem tenetur voluptatem commodi reprehenderit unde aut earum suscipit voluptatum ratione vel voluptatibus rem delectus dolorum quo, officia aperiam aliquid, itaque nihil magni quasi ad. Quidem.
                 Voluptatum tenetur illum a suscipit consequuntur mollitia sequi distinctio consectetur quo ratione facere, totam dolores ipsam. Ea quasi animi dolorem harum corrupti eius, nesciunt ratione incidunt possimus sint explicabo cum?
                 Minus, autem. Odit voluptatibus labore beatae aliquam rerum, voluptates debitis totam animi cum atque quia minima magni tempora laudantium exercitationem fuga? Perspiciatis eos, asperiores omnis suscipit esse eligendi molestias temporibus!
                 Nihil quasi aut perferendis, quibusdam dolorem nesciunt cumque, consequuntur totam dolore blanditiis repudiandae doloremque a, quidem ullam amet. Porro quia officia esse atque ea debitis ipsam sequi laborum deleniti labore?
                 A, fugiat quisquam eius veniam praesentium itaque maiores obcaecati amet consectetur, magni explicabo molestiae quo, pariatur cumque! Asperiores odio sint quae, esse tempora, provident quidem neque impedit harum saepe quos.
                 Ut quae, numquam qui aliquam non suscipit. Dolore blanditiis labore nobis odio earum minima cupiditate, quisquam consequatur saepe eius vitae, deserunt culpa numquam eaque recusandae commodi ipsam quia ratione illum.
                 Alias reprehenderit ipsa sint atque, veniam dicta delectus necessitatibus modi hic, eveniet itaque nihil nostrum labore dolor possimus nobis repellendus ullam placeat soluta, iure doloremque fuga? Reprehenderit explicabo itaque rerum.
                 Exercitationem tenetur incidunt necessitatibus delectus quasi nobis provident, vero, impedit, laboriosam perspiciatis officiis totam quo nulla repellat dolore illo assumenda modi! Est commodi in quam excepturi beatae illo dolorem nam.
                 Officiis recusandae veritatis culpa, quasi nobis incidunt a. Consequatur aliquid sit amet culpa, numquam inventore omnis expedita id veritatis alias, debitis soluta eos odio maxime, earum voluptas officiis aperiam laborum?
                 Delectus esse possimus expedita corporis rerum soluta dolorem, assumenda quam distinctio similique officia. Suscipit necessitatibus facere recusandae minus sequi aspernatur temporibus, nemo veniam. Vel asperiores aspernatur iste obcaecati numquam nulla.
                 Saepe ipsa voluptas voluptates, vitae officiis atque totam, rerum reprehenderit eos eius assumenda nam temporibus possimus, iusto perferendis molestias molestiae blanditiis necessitatibus maxime repellendus odio quis! Maxime cum velit aspernatur.
                 Hic, nesciunt sequi. Voluptate deserunt rerum tenetur temporibus? Eum deserunt omnis, error ipsum asperiores hic quam atque quos cum aliquam consequuntur dolore mollitia ut adipisci enim, accusamus vitae pariatur! Ratione.
                 Esse, voluptates. Vero tenetur obcaecati autem in quo repudiandae magni modi voluptatum, optio ipsa facilis eligendi. Officia, quas aspernatur blanditiis qui voluptatibus nobis laborum consequuntur tempore perspiciatis obcaecati laboriosam debitis.
                 Temporibus laudantium tenetur, suscipit culpa repudiandae cumque ullam consequatur nostrum neque architecto eligendi rerum perspiciatis laboriosam sed. Est mollitia recusandae ex voluptatem consectetur nam. Dicta ea libero doloremque dolores eveniet!
                 Neque assumenda est cupiditate itaque provident dolor architecto fuga ea, praesentium ipsum quaerat sequi quos possimus, quod esse molestiae officia excepturi alias totam quam vitae repellat adipisci corporis similique. Perspiciatis.
                 Est eligendi ullam placeat velit modi fugiat animi! Voluptate soluta et adipisci architecto, beatae iste accusamus minus repellendus vel! Eos neque ipsum nihil dolores eius, assumenda consectetur natus perspiciatis magni?
                 Nesciunt, modi? Exercitationem ea voluptatum tempore rem aliquid eligendi pariatur, eum, similique, alias ut nisi quam. Aliquid quae perspiciatis ipsum repellendus, ex obcaecati inventore voluptate sed hic eum, aliquam corrupti.
                 Nulla, provident, ipsum voluptatem sequi deleniti omnis ullam pariatur dolore dolores dolorem quos quod, deserunt facilis a excepturi nesciunt inventore quasi. Aliquam blanditiis nisi perferendis! Vel ipsum iste quo exercitationem.
                 Maiores animi ab voluptas ut, fuga qui repellendus numquam quam sunt porro quibusdam. Deserunt totam blanditiis quibusdam facilis maiores perferendis ipsa quaerat deleniti, eos repellendus sit illo quis saepe magnam.
                 Cum, reiciendis illum. Quos necessitatibus omnis est, natus rem commodi quasi quod maiores quaerat ipsam ipsum mollitia cupiditate saepe possimus veniam ut odio. Veniam nesciunt harum a, optio aut exercitationem.
                 Facere dicta harum cumque exercitationem nulla asperiores, excepturi reiciendis adipisci? Eum maiores voluptas necessitatibus asperiores libero debitis eligendi praesentium corrupti excepturi est expedita neque quasi, error quaerat nisi, voluptatibus molestias.
                 Beatae eum alias illo perspiciatis omnis minima illum odio in fugiat veritatis iusto cumque id quas quisquam, repellat eius corrupti facere libero, mollitia incidunt dolores et, numquam sit veniam! Ab.
                 Quo eaque, repudiandae temporibus praesentium voluptas corporis? Assumenda saepe sapiente veritatis inventore cumque culpa ex ipsam a itaque eveniet. Voluptates dolore distinctio expedita incidunt hic aut quia dolor labore pariatur.
                 Et non id perferendis impedit vitae sapiente veritatis, laboriosam enim! Tenetur in, illum alias accusamus aliquam aliquid incidunt necessitatibus asperiores ipsam similique officiis iusto deleniti impedit consectetur perspiciatis cum eos?
                 Explicabo culpa eum voluptates nostrum quisquam? Distinctio, delectus quisquam nam in blanditiis error sunt deserunt est consectetur obcaecati expedita repellendus ipsum autem vero labore. Adipisci hic quae iste praesentium consequatur.
                 Doloremque voluptatum facilis, adipisci vel delectus ad accusamus distinctio laborum alias optio architecto enim aliquid non ipsum qui fugiat sint illo quos veniam dolor quaerat, est omnis. Doloribus, voluptates officiis.
                 Harum amet deleniti quas deserunt sapiente nostrum aliquam culpa temporibus sequi quibusdam tempora explicabo reprehenderit neque dolor ipsa, excepturi eveniet sit quam, et id. Debitis earum omnis delectus. Incidunt, accusantium?
                 Incidunt necessitatibus, veniam aut quam consequatur temporibus iusto ullam explicabo ea ad repudiandae laborum voluptatibus, cupiditate enim. Consequuntur veniam suscipit exercitationem placeat itaque tenetur similique, sunt, eaque tempora ea consectetur!
                 Aspernatur dolores tempore alias accusantium voluptates iusto sit tempora, accusamus maiores, enim quis libero est eligendi deleniti error! Omnis, fugit consequuntur. Porro fuga, doloremque sit illo omnis optio sint ut!
                 Voluptate sapiente aliquid laudantium doloribus voluptatum eum. Cumque sed fugiat placeat consequuntur alias vero consequatur, repellendus magnam eaque. Dicta, velit? Explicabo sunt aliquam quam dicta at, fugit iusto iure magnam.
                 Quam, debitis ut? Saepe dicta sapiente, similique aperiam explicabo officia cumque aliquam praesentium iusto blanditiis repellat illo sint nulla? Libero est natus culpa qui! Nulla beatae quibusdam eaque asperiores. Voluptatum.
                 Aliquam inventore ipsam assumenda eaque possimus, dolorem distinctio voluptates autem voluptate magni non odio magnam laboriosam doloremque! Voluptatum fuga, mollitia officia rem assumenda reiciendis exercitationem consequuntur, quia, quos voluptas totam.
                 Quam, eos, doloribus sint modi porro vel commodi culpa vitae incidunt sed facere, a at qui veritatis deserunt corporis dicta accusantium vero ipsum animi tempore iste quibusdam? Voluptatem, iure neque!
                 Nesciunt ut accusantium rem voluptatibus excepturi magni laborum natus voluptatem veniam harum, optio similique provident officiis ipsam deleniti vel dicta eius tempora blanditiis, eveniet adipisci iusto cum! At, sapiente alias!
                 Illum consequatur voluptas suscipit atque eligendi itaque nobis numquam voluptatem tenetur incidunt repellat est rerum maxime, blanditiis explicabo vel harum dicta unde quaerat porro quo dolore praesentium! Fugiat, fugit sequi?
                 Laborum a cumque numquam repudiandae perspiciatis atque distinctio non necessitatibus magnam possimus amet iste beatae, nobis temporibus ex illum aut nisi nulla sapiente maxime ad in ipsam! Laborum, labore neque.
                 Odit, natus. Voluptates iure molestiae esse! Obcaecati est ut delectus, voluptatum deserunt vel quasi! Eum fuga ratione adipisci velit pariatur saepe quo eveniet neque quisquam, similique molestias dolor facere incidunt.
                 </div>
                   </div>
             <div className="man-img">
                 <img className="man-img" src={manImg} alt="man"/>
             </div>
            </div>
        </div>
    )
}
